language: 
  - python

install:
  - pip install pytest codecov coverage

script:
  - python3 -m pytest --color=yes --verbose Z_tests/

notifications:
  email:
    recipients:
      thisisshub@gmail.com
    on_success: never
    on_failure: always