language: 
  - python

install:
  - pip install pytest-cov pytest codecov

script:
  - python3 -m pytest --color=yes --verbose tests/

env:
  - CODECOV_TOKEN="1903b100-26fd-48df-9d9a-3ec9b67e2556"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      thisisshub@gmail.com
    on_success: never
    on_failure: always