language: 
  - python

install:
  - pip install pytest coverage

script:
  - python3 -m pytest --color=yes --verbose tests/
  - python3 -m coverage run -m pytest .


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      thisisshub@gmail.com
    on_success: never
    on_failure: always