language: 
  - python

install:
  - pip install pytest codecov coverage

script:
  - python3 -m pytest --color=yes --verbose tests/
  - python3 -m pytest --verbose --color=yes --cov=. --assert=plain


after_success:
  - codecov

notifications:
  email:
    recipients:
      thisisshub@gmail.com
    on_success: never
    on_failure: always