language: 
  - python

install:
  - pip install pytest-cov pytest codecov

script:
  - python3 -m pytest --color=yes --verbose tests/
  - coverage run -m unittest discover


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      thisisshub@gmail.com
    on_success: never
    on_failure: always